### ISSUE TITLE
The demo test results don't seem to be enhanced?

### ISSUE THREAD

**Issue by HZY12345** [SJTU-ViSYS/FeatureBooster#10]
Hello and thank you very much for this work. I tested the effect of ORB feature enhancement before and after using the trained model in your open source project, the test results are as follows, but it seems that the original ORB feature and the ORB feature effect after using the model enhancement are the same, what is going on?

![Screenshot from 2023-12-12 15-11-29](https://github.com/SJTU-ViSYS/FeatureBooster/assets/74952599/9937c622-270b-4267-a56c-9a175a81adbe)
![Screenshot from 2023-12-12 15-11-48](https://github.com/SJTU-ViSYS/FeatureBooster/assets/74952599/98ce76f1-638e-4c87-973c-02fd0062aee7)

**Comment by Antu3heng** [comment]
Hello, @HZY12345 . Based on the results you've posted, it seems like the result of ORB+Boost-B is also misinterpreted as the result of ORB. This is the result from https://github.com/SJTU-ViSYS/FeatureBooster/blob/main/hpatches_sequences/HPatches-Sequences-Matching-Benchmark.ipynb.
![image](https://github.com/SJTU-ViSYS/FeatureBooster/assets/38786063/a97cfb35-c546-4943-93af-4967465436cf)

Maybe you can delete the cached npz file of ORB and ORB+Boost-B, then following the instruction of [evaluation-on-hpatches](https://github.com/SJTU-ViSYS/FeatureBooster/tree/main?tab=readme-ov-file#evaluation-on-hpatches) again. For ORB extraction, you can run `python extract_features.py --descriptor ORB --image_list_file image_list_hpatches_sequences.txt`. For ORB+Boost-B extraction, you can run `python extract_features.py --descriptor ORB+Boost-B --image_list_file image_list_hpatches_sequences.txt`.

And please check the cell-4 in HPatches-Sequences-Matching-Benchmark.ipynb, make sure the names and the methods are setting correctly as this:
![image](https://github.com/SJTU-ViSYS/FeatureBooster/assets/38786063/3618520c-c375-4315-8598-1e43c302d816)

**Comment by HZY12345** [comment]
@Antu3heng，Thank you for your help. I have achieved the same experimental results as in the paper after following your suggestions.
Sorry, I have another question. Do you think ORB feature matching enhanced with this algorithm has advantages over optical flow matching? I plan to use this method to replace the optical flow matching in my SLAM system. Do you think this plan is feasible?

**Comment by Antu3heng** [comment]
> @Antu3heng，Thank you for your help. I have achieved the same experimental results as in the paper after following your suggestions. Sorry, I have another question. Do you think ORB feature matching enhanced with this algorithm has advantages over optical flow matching? I plan to use this method to replace the optical flow matching in my SLAM system. Do you think this plan is feasible?

Hi, @HZY12345. Sorry for the late reply. I think that optical flow tracking is lightweight, fast, and more suitable for fast-moving motion, while descriptor-based matching is more time-consuming but also more suitable for wide-baseline matching which can help long-term data association such as loop closuring and relocalization. Hope it helps.

**Comment by Antu3heng** [comment]
Closed due to no longer being active. Can be reopened at any time.
