### ISSUE TITLE
There was a problem with testing the SIFT feature

### ISSUE THREAD

**Issue by HZY12345** [SJTU-ViSYS/FeatureBooster#11]

**Comment by Antu3heng** [comment]
Closed due to no longer being active. Can be reopened at any time.

**Comment by bbbugg** [comment]
In Sift.py, the extract function return two numpy.ndarray. 
> def extract(self, *args, **kwargs): # real signature unknown; restored from \__doc\__
>         """
>         extract(*args, **kwargs)
>         Overloaded function.
>         
>         1. extract(self: pycolmap.Sift, image: numpy.ndarray[numpy.uint8[m, n], flags.c_contiguous]) -> Tuple[numpy.ndarray[numpy.float32[m, 4]], numpy.ndarray[numpy.float32[m, n]]]
>         
>         2. extract(self: pycolmap.Sift, image: numpy.ndarray[numpy.float32[m, n], flags.c_contiguous]) -> Tuple[numpy.ndarray[numpy.float32[m, 4]], numpy.ndarray[numpy.float32[m, n]]]
>         """
>         pass
But in dog.py, `keypoints, scores, descriptors = self.sift.extract(img)`. Only two values were returned, while the code expects it to return three values.
![image](https://github.com/user-attachments/assets/a208576d-8d39-45f2-bb46-7080716fa288)
