### ISSUE TITLE
orbslam2   

### ISSUE THREAD

**Issue by molong-d** [SJTU-ViSYS/FeatureBooster#12]
Hello author, thank you for your excellent work. I utilized your code to enhance the ORB features and incorporated them into ORBSLAM2 after feature extraction.
But after putting it in, I found that the system is more likely to track failures, why is that?
What solutions do you think there are? (Is it related to word bags? Do I need to retrain?)

**Comment by Antu3heng** [comment]
Yes. The vocabulary needs to be retrained since the ORBmatcher uses the BoW to accelerate the feature matching. By the way, we have uploaded our pre-trained vocabulary [here](https://github.com/SJTU-ViSYS/FeatureBooster/blob/main/bow_voc/ORB%2BBoost-B_voc.tar.gz).

Besides, you can also try to test different matching ratios and thresholds in ORBmatcher while we use the same value as the original ORBSLAM2 used.

**Comment by molong-d** [comment]
Thank you, thank you for your excellent work and selfless response. Thank you very much, and I wish you more excellent articles. Thank you again

**Comment by molong-d** [comment]
Thank you for your answer. Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xinjiang ***@***.***&gt;; 
发送时间: 2024年1月25日(星期四) 晚上7:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SJTU-ViSYS/FeatureBooster] orbslam2    (Issue #12)





 
Closed #12 as completed.

**Comment by molong-d** [comment]
Hello author, I have added the module to the ORBSLAM2 system as you suggested, but the improvement is not significant or even slightly worse. May I ask if your improvement is significant? Is it my mistake

**Comment by molong-d** [comment]
Hello author, I have added the module to the ORBSLAM2 system as you suggested, but the improvement is not significant or even slightly worse. May I ask if your improvement is significant? Is it my mistake




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SJTU-ViSYS/FeatureBooster"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月25日(星期四) 晚上7:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SJTU-ViSYS/FeatureBooster] orbslam2    (Issue #12)





 
Closed #12 as completed.

**Comment by qinqi-mm** [comment]
> Hello author, I have added the module to the ORBSLAM2 system as you suggested, but the improvement is not significant or even slightly worse. May I ask if your improvement is significant? Is it my mistake

大佬您好，冒昧地打扰您一下，请问您最后slam的效果有优化好嘛？
