### ISSUE TITLE
CMake Error at pybind11/tools/FindPythonLibsNew.cmake:99

### ISSUE THREAD

**Issue by snowflakezzz** [SJTU-ViSYS/FeatureBooster#17]
Thank you for your excellent work.
When I build orbslam2_features, and run "cmake "

I met the issue:
"CMake Error at pybind11/tools/FindPythonLibsNew.cmake:99 (message):
  Python config failure:            "
![Screenshot from 2024-02-29 10-14-13](https://github.com/SJTU-ViSYS/FeatureBooster/assets/55946065/b339cfc7-aacf-4ee7-8d0c-6e36de41316b)

And I found out that it was an issue with "execute_process" in FindPythonLibsNew.cmake
![Screenshot from 2024-02-29 10-19-26](https://github.com/SJTU-ViSYS/FeatureBooster/assets/55946065/0711de79-27b5-42bc-8068-59442bec2e91)

So I test these codes, it can work fine.
![Screenshot from 2024-02-29 10-12-37](https://github.com/SJTU-ViSYS/FeatureBooster/assets/55946065/90855cb0-a26c-4390-a7ae-e3e38cfb87b9)

Do you know how to solve this problem?

**Comment by snowflakezzz** [comment]
I solved this problem through: https://github.com/pybind/pybind11/pull/2196

**Comment by snowflakezzz** [comment]
If you solve this problem throng https://github.com/pybind/pybind11/pull/2196, you will found that you can't generate *.so file though compilation succeeded. 

You better solve upper problem through updating pybind to the latest official version.

**Comment by zzyue0504** [comment]
Hello, I have encountered the same problem. Have you solved it yet?

**Comment by snowflakezzz** [comment]
（自动回复）邮件已收到~

**Comment by snowflakezzz** [comment]
> Hello, I have encountered the same problem. Have you solved it yet?

you need to update your pybind to the latest official version.
