### ISSUE TITLE
Hello author, may I ask which operating system the project is running on?

### ISSUE THREAD

**Issue by zzyue0504** [SJTU-ViSYS/FeatureBooster#19]

**Comment by Antu3heng** [comment]
We have tested the training codes on Ubuntu 18.04 and Ubuntu 20.04.

**Comment by zzyue0504** [comment]
> We have tested the training codes on Ubuntu 18.04 and Ubuntu 20.04.

OK, thank you very much. And another question is, do we need to install OpenCV before building the ORBSLAM2 features?

**Comment by zzyue0504** [comment]
OK, thank you very much. Another question is, do we need to install OpenCV before building the ORBSLAM2 features?

**Comment by Antu3heng** [comment]
Yes, the OpenCV is required.

**Comment by zzyue0504** [comment]
OK! Thanks a lot!
