### ISSUE TITLE
Demo code

### ISSUE THREAD

**Issue by TuanTNG** [SJTU-ViSYS/FeatureBooster#2]
Hi,
Thank you for your excellent work.

Can you provide a Python script that can run inference from 2 images?
By the way, have you tested the end-2-end inference speed?

Looking forward to hearing from you soon.

**Comment by Antu3heng** [comment]
Hi. Sorry for the late response. 

> Can you provide a Python script that can run inference from 2 images?

For the demo code, you can refer to our Jupyter Notebook scripts in `qualitative/qualitative-matches.ipynb`. It provides a example for matching a pair of images using different features.

> have you tested the end-2-end inference speed?

We mainly tested the runtime of ALIKE-L on Jetson Xavier NX. It took about 125ms for the extraction of ALIKE, and our **_FeatureBooster_** took extra 46ms to get the ALIKE+Boost-X.

Besides, by using our Jupyter Notebook scripts in `qualitative/qualitative-matches.ipynb`, you can easily to tested the end-to-end inference speed by yourself.
