### ISSUE TITLE
questions about Visual Localization(Aachen Day-Night dataset v1.1)

### ISSUE THREAD

**Issue by July0928** [SJTU-ViSYS/FeatureBooster#4]
Is Aachen Day-Night dataset v1.1 only testdataset? i have trained on Megadepth dataset, how can i get the result of visual localization?

**Comment by Antu3heng** [comment]
Hi. I'm sorry for not getting back to you sooner. Yes, the Aachen Day-Night dataset v1.1 is only used for testing. As for the result of visual localization on this dataset, you can refer to the instructions of these repos: [visuallocalizationbenchmark](https://github.com/tsattler/visuallocalizationbenchmark) and [HLOC](https://github.com/cvg/Hierarchical-Localization), and then submit the localization result to [www.visuallocalization.net](www.visuallocalization.net) for the localization error.

**Comment by Antu3heng** [comment]
@NingxiaoJian Please see Issue #5.

**Comment by Antu3heng** [comment]
Closed due to no longer being active. Can be reopened at any time.
